from typing import Dict, Mapping, Optional, Tuple

PYTHON_INTERFACE_VERSION: int
TRAQULA_VERSION: int
TERRAIN_VERSION: int
RUST_PACKAGE_VERSION: str

class PositoriumError(Exception): ...
class ConfigurationError(PositoriumError): ...
class PersistenceError(PositoriumError): ...
class DataCorruptionError(PositoriumError): ...
class ParseError(PositoriumError): ...
class ExecutionError(PositoriumError): ...
class CancelledError(PositoriumError): ...
class QueryTimeoutError(PositoriumError): ...
class ResourceLimitError(PositoriumError): ...
class InvalidQueryError(PositoriumError): ...
class InternalError(PositoriumError): ...
class ClosedError(PositoriumError): ...

class _Database:
    @staticmethod
    def memory() -> _Database: ...
    @staticmethod
    def open(path: str) -> _Database: ...
    @property
    def closed(self) -> bool: ...
    def execute_json(
        self,
        script: str,
        parameters: Optional[Mapping[str, Tuple[str, str]]] = ...,
        now: Optional[str] = ...,
        timeout: Optional[float] = ...,
        max_rows: Optional[int] = ...,
    ) -> str: ...
    def terrain_json(
        self,
        as_of: Optional[str] = ...,
        timeout: Optional[float] = ...,
        projected_role_limit: Optional[int] = ...,
        max_relationship_signatures: Optional[int] = ...,
    ) -> str: ...
    def close(self) -> None: ...
